In [1]:
X_centered=X-X.mean(axis=0)
U,s,V=np.linalg.svd(X_centered)
c1=V.T[:,0]
c2=V.T[:,1]

NameError: name 'X' is not defined

In [ ]:
from sklearn.decomposition import PCA

pca=PCA(n_components=2)
X2D=pca.fit_transform(X)

In [ ]:
pca=PCA(n_components=0.95)
X_reduced=pca.fit_transform(X)

In [5]:
import numpy as np

In [6]:
ration=np.array([0.84248607, 0.14631839])

In [7]:
ration

array([0.84248607, 0.14631839])

In [8]:
cumsum=np.cumsum(ration)

In [9]:
cumsum

array([0.84248607, 0.98880446])

In [15]:
for X_batch in np.array_split(ration,1):
    print(X_batch)

[0.84248607 0.14631839]


In [18]:
from sklearn.decomposition import KernelPCA

rbf_pca=KernelPCA(n_components=2,kernel='rbf',gamma=0.04)

In [19]:
from sklearn.model_selection import GridSearchCV 
from sklearn.linear_model import LogisticRegression 
from sklearn.pipeline import Pipeline

clf = Pipeline([
        ("kpca", KernelPCA(n_components=2)),
        ("log_reg", LogisticRegression())
])
param_grid = [{
        "kpca__gamma": np.linspace(0.03, 0.05, 10),
        "kpca__kernel": ["rbf", "sigmoid"]
    }]
grid_search = GridSearchCV(clf, param_grid, cv=3)

In [20]:
np.linspace(0.03, 0.05, 10)

array([0.03      , 0.03222222, 0.03444444, 0.03666667, 0.03888889,
       0.04111111, 0.04333333, 0.04555556, 0.04777778, 0.05      ])